"""
video_generator.py — Explainer Video Generation
================================================
Creates a slide-style MP4 explainer video using:
  - Pillow (PIL) to render text slides as images
  - MoviePy to assemble images + audio into a video
  - gTTS/Coqui to generate narration audio (optional)

Course: Advanced Topics in Machine Learning (HTML)
"""

import logging
import textwrap
from pathlib import Path
from typing import List, Tuple

import nltk

log = logging.getLogger(__name__)

# Output video settings
VIDEO_W, VIDEO_H = 1280, 720
SLIDE_DURATION   = 6
FPS              = 24
FONT_SIZE_TITLE  = 36
FONT_SIZE_BODY   = 28

# Colors
BG_COLOR     = (11, 17, 32)
ACCENT_COLOR = (245, 158, 11)
BODY_COLOR   = (176, 190, 197)
TITLE_COLOR  = (240, 244, 248)


# ─── PIL SLIDE RENDERING ────────────────────────────────────────

def _get_font(size: int, bold: bool = False):
    from PIL import ImageFont
    font_candidates = [
        "C:/Windows/Fonts/arialbd.ttf" if bold else "C:/Windows/Fonts/arial.ttf",
        "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf" if bold else
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
        "/System/Library/Fonts/Helvetica.ttc",
    ]
    for path in font_candidates:
        if Path(path).exists():
            try:
                return ImageFont.truetype(path, size)
            except Exception:
                pass
    return ImageFont.load_default()


def render_slide(title: str, body: str, slide_num: int, total: int):
    from PIL import Image, ImageDraw

    img  = Image.new("RGB", (VIDEO_W, VIDEO_H), BG_COLOR)
    draw = ImageDraw.Draw(img)

    # Grid background
    grid_color = (17, 24, 39)
    for x in range(0, VIDEO_W, 48):
        draw.line([(x, 0), (x, VIDEO_H)], fill=grid_color, width=1)
    for y in range(0, VIDEO_H, 48):
        draw.line([(0, y), (VIDEO_W, y)], fill=grid_color, width=1)

    # Amber left accent bar
    draw.rectangle([48, 80, 54, VIDEO_H - 80], fill=ACCENT_COLOR)

    # Slide counter
    counter_font = _get_font(16)
    draw.text((VIDEO_W - 80, 30), f"{slide_num} / {total}",
              font=counter_font, fill=(75, 85, 99))

    # Title
    title_font = _get_font(FONT_SIZE_TITLE, bold=True)
    title_y    = 100
    draw.text((80, title_y), title, font=title_font, fill=TITLE_COLOR)

    # Amber underline
    title_bbox = draw.textbbox((80, title_y), title, font=title_font)
    draw.line([(80, title_bbox[3] + 8), (title_bbox[2], title_bbox[3] + 8)],
              fill=ACCENT_COLOR, width=2)

    # Body text
    body_font = _get_font(FONT_SIZE_BODY)
    wrapped   = textwrap.fill(body, width=65)
    draw.multiline_text((80, title_bbox[3] + 32), wrapped,
                        font=body_font, fill=BODY_COLOR, spacing=10)

    # Branding
    brand_font = _get_font(18)
    draw.text((80, VIDEO_H - 40), "ScholarAI · Advanced Topics in ML",
              font=brand_font, fill=(55, 65, 81))

    return img


# ─── SLIDE SEGMENTATION ─────────────────────────────────────────

def _segment_summary(summary: str, sentences_per_slide: int = 3) -> List[Tuple[str, str]]:
    try:
        sentences = nltk.sent_tokenize(summary)
    except Exception:
        sentences = summary.split(". ")

    slides = [("Document Summary", "Generated by ScholarAI ML Pipeline")]
    chunks = [sentences[i:i + sentences_per_slide]
              for i in range(0, len(sentences), sentences_per_slide)]

    for i, chunk in enumerate(chunks):
        slides.append((f"Key Point {i + 1}", " ".join(chunk)))

    slides.append(("End of Summary",
                   "Generated by ScholarAI · Powered by BART + Sentence-BERT"))
    return slides


# ─── VIDEO ASSEMBLY ─────────────────────────────────────────────

def generate_video(summary: str, output_path: str) -> str:
    try:
        from moviepy.editor import ImageClip, AudioFileClip, concatenate_videoclips
        from PIL import Image
        import numpy as np

        segments = _segment_summary(summary, sentences_per_slide=3)
        log.info(f"Rendering {len(segments)} slides…")

        clips = []
        for i, (title, body) in enumerate(segments):
            pil_img   = render_slide(title, body, i + 1, len(segments))
            img_array = np.array(pil_img)
            clip = ImageClip(img_array).set_duration(SLIDE_DURATION).set_fps(FPS)
            clip = clip.fadein(0.5).fadeout(0.5)
            clips.append(clip)

        final = concatenate_videoclips(clips, method="compose")

        # Try to add TTS narration audio
        audio_path = output_path.replace(".mp4", "_narration.mp3")
        audio_clip = None
        try:
            from .tts_generator import generate_audio
            generate_audio(summary, audio_path)

            if Path(audio_path).exists() and Path(audio_path).stat().st_size > 500:
                audio_clip = AudioFileClip(audio_path)
                video_dur  = final.duration
                audio_dur  = audio_clip.duration

                if audio_dur < video_dur:
                    audio_clip = audio_clip.audio_loop(duration=video_dur)
                else:
                    audio_clip = audio_clip.subclip(0, video_dur)

                final = final.set_audio(audio_clip)
                log.info("Audio added to video.")

        except Exception as e:
            audio_exists = Path(audio_path).exists()
            audio_size = Path(audio_path).stat().st_size if audio_exists else 0
            log.warning(f"Could not add audio to video: {type(e).__name__}: {e}")
            log.warning(f"Audio path details: {audio_path} exists={audio_exists} size={audio_size}")

        # Export MP4
        final.write_videofile(
            output_path,
            fps=FPS,
            codec="libx264",
            audio_codec="aac",
            temp_audiofile=output_path + ".temp.m4a",
            remove_temp=True,
            logger=None,
            verbose=False
        )

        # Cleanup — close audio clip before deleting on Windows
        if audio_clip is not None:
            try:
                audio_clip.close()
            except Exception:
                pass

        try:
            if Path(audio_path).exists():
                Path(audio_path).unlink()
        except Exception as e:
            log.warning(f"Could not delete temp audio (Windows lock): {e}")

        log.info(f"Video saved → {output_path}")
        return output_path

    except ImportError as e:
        log.warning(f"MoviePy/PIL not available: {e}. Writing placeholder.")
        return _write_slideshow_fallback(summary, output_path)
    except Exception as e:
        log.error(f"Video generation failed: {e}", exc_info=True)
        return _write_slideshow_fallback(summary, output_path)


# ─── FALLBACK: SLIDES ZIP ───────────────────────────────────────

def _write_slideshow_fallback(summary: str, output_path: str) -> str:
    try:
        from PIL import Image
        import io, zipfile

        segments = _segment_summary(summary)
        zip_path = output_path.replace(".mp4", "_slides.zip")

        with zipfile.ZipFile(zip_path, "w") as zf:
            for i, (title, body) in enumerate(segments):
                pil_img = render_slide(title, body, i + 1, len(segments))
                buf = io.BytesIO()
                pil_img.save(buf, format="PNG")
                zf.writestr(f"slide_{i+1:02d}.png", buf.getvalue())

        log.info(f"Slideshow ZIP saved → {zip_path}")
        Path(output_path).write_text(f"[Video slides exported as {zip_path}]")
        return output_path

    except Exception:
        Path(output_path).write_text(
            "[PLACEHOLDER] Install moviepy and pillow to generate video.\n"
            f"Summary:\n{summary[:400]}"
        )
        return output_path